"""empty message

Revision ID: 3d8ba473571f
Revises: 
Create Date: 2023-09-20 12:23:15.893715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8ba473571f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Auth_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_data', sa.String(length=1264), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ToolId',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=1264), nullable=True),
    sa.Column('client_id', sa.String(length=625), nullable=True),
    sa.Column('client_secret', sa.String(length=625), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entity_data_read_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=64), nullable=True),
    sa.Column('last_read_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_name')
    )
    op.create_table('job_data_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('input_records', sa.Integer(), nullable=True),
    sa.Column('output_records', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_execution_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('myob_account', sa.String(length=255), nullable=True),
    sa.Column('xero_account', sa.String(length=255), nullable=True),
    sa.Column('input_account_id', sa.Integer(), nullable=True),
    sa.Column('output_account_id', sa.Integer(), nullable=True),
    sa.Column('qbo_account', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=255), nullable=True),
    sa.Column('end_date', sa.String(length=255), nullable=True),
    sa.Column('functions', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=1024), nullable=True),
    sa.Column('is_successful', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('myob_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=655), nullable=True),
    sa.Column('client_secret', sa.String(length=655), nullable=True),
    sa.Column('access_token', sa.String(length=5000), nullable=True),
    sa.Column('refresh_token', sa.String(length=5000), nullable=True),
    sa.Column('company_file_uri', sa.String(length=255), nullable=True),
    sa.Column('company_file_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qbo_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=625), nullable=True),
    sa.Column('client_secret', sa.String(length=625), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('minor_version', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=5000), nullable=True),
    sa.Column('refresh_token', sa.String(length=5000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=1264), nullable=True),
    sa.Column('keys', sa.String(length=5255), nullable=True),
    sa.Column('account_type', sa.String(length=255), nullable=True),
    sa.Column('tool_type', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xero_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('xero_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=625), nullable=True),
    sa.Column('client_secret', sa.String(length=625), nullable=True),
    sa.Column('scopes', sa.String(length=1000), nullable=True),
    sa.Column('re_directURI', sa.String(length=1000), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=5000), nullable=True),
    sa.Column('refresh_token', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('function_name', sa.String(length=1264), nullable=True),
    sa.Column('is_successful', sa.Integer(), nullable=True),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.Column('write', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('keys', sa.Text(), nullable=True),
    sa.Column('values', sa.Text(), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_execution_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_execution_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(length=500), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_execution_steps')
    op.drop_table('task_execution_status')
    op.drop_table('tool_settings')
    op.drop_table('task')
    op.drop_table('xero_settings')
    op.drop_table('tool')
    op.drop_table('qbo_settings')
    op.drop_table('myob_settings')
    op.drop_table('jobs')
    op.drop_table('job_execution_status')
    op.drop_table('job_data_count')
    op.drop_table('entity_data_read_details')
    op.drop_table('Users')
    op.drop_table('ToolId')
    op.drop_table('Auth_data')
    # ### end Alembic commands ###
