MDB_USERNAME = "root"
MDB_PASSWORD = "Technology_100"
MYOB_KEY = "client_id,client_secret,company_file_uri,company_file_id,refresh_token,access_token,redirect_uri"
QBO_KEY = "client_id,client_secret,base_url,company_id,minor_version,User_Agent,access_token,refresh_token"
XERO_KEY = "client_id,client_secret,refresh_token,access_token,xero-tenant-id,re_directURI,scopes,state"
MYOBLEDGER_KEY = "client_id,client_secret,company_file_uri,company_file_id,refresh_token,access_token,redirect_uri"
RECKON_KEY = "client_id,client_secret,id_secret_encoded,redirect_url,username,password,Ocp-Apim-Subscription-Key,token,refresh_token,url,book"
EXCEL_KEY = ""
DELETE_KEY = ""
EXCEL = "Excel"
MYOB = "Myob"
QBO = "Qbo"
XERO = "Xero"
DELETE = "Delete"
RECKON = "Reckon"
MYOBLEDGER = "Myobledger"
JOB_STATUS_SUCCESSFUL = '1'
JOB_STATUS_IN_PROGRESS = '2'
JOB_STATUS_NOT_STARTED = '3'
JOB_STATUS_FAILED = '4'
XERO_REDIRECT = "https://mmc.vishleshak.io/create_auth_code"
QBO_REDIRECT = "https://mmc.vishleshak.io/data_access"
# XERO_REDIRECT='http://localhost:5000/create_auth_code'
# QBO_REDIRECT='http://localhost:5000/data_access'
XERO_CI = "BDDDE967BCF943098B8A44E164AE1A74"
XERO_CS= "JVCy3rDSvqkMelGOxJenpLkdiAgRgiHcXLe6GJZ79IAKXv_l"
QBO_CI = 'ABO1DrhwFGD0Juq2zKElAFgAxeY9PXLdH4xmNxDURVJJt8QbiS'
QBO_CS = 'sZdaiuAzUIP8DEf2OhFv76tRZTX1PE1vWtTqahEK'
QBO_BaseURL = "https://quickbooks.api.intuit.com"

# QBO_CI='ABpWOUWtcEG1gCun5dQbQNfc7dvyalw5qVF97AkJQcn5Lh09o6'
# QBO_CS='LepyjXTADW592Dq5RYUP8UbGLcH5xtqDQhrf2xJN'
Queue_URI='https://sqs.your-aws-region.amazonaws.com/074206019712/MmcSelfServiceEmail'

NODE_APP_URL="http://localhost:6000"
XERO_SCOPE='openid%20profile%20email%20accounting.transactions%20accounting.contacts%20accounting.settings%20payroll.employees%20accounting.journals.read%20payroll.employees.read%20accounting.transactions.read%20offline_access%20accounting.reports.read%20payroll.payruns%20payroll.payruns.read%20payroll.payslip%20payroll.payslip.read%20payroll.settings%20payroll.settings.read%20assets%20assets.read'
aws_access_key_id1 = 'AKIARCRYGACABFYEF6O3'
aws_secret_access_key1 = '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'
region_name1 = 'ap-south-1'