MDB_USERNAME = "root"
MDB_PASSWORD = "mmg"
MYOB_KEY = "client_id,client_secret,company_file_uri,company_file_id,refresh_token,access_token,redirect_uri"
QBO_KEY = "client_id,client_secret,base_url,company_id,minor_version,User_Agent,access_token,refresh_token"
XERO_KEY = "client_id,client_secret,refresh_token,access_token,xero-tenant-id,re_directURI,scopes,state"
MYOBLEDGER_KEY = "client_id,client_secret,company_file_uri,company_file_id,refresh_token,access_token,redirect_uri"
RECKON_KEY = "client_id,client_secret,id_secret_encoded,redirect_url,username,password,Ocp-Apim-Subscription-Key,token,refresh_token,url,book"
EXCEL_KEY = ""
DELETE_KEY =""
EXCEL = "Excel"
MYOB = "Myob"
QBO = "Qbo"
XERO = "Xero"
DELETE ="Delete"
RECKON ="Reckon"
MYOBLEDGER = "Myobledger"
JOB_STATUS_SUCCESSFUL = '1'
JOB_STATUS_IN_PROGRESS= '2'
JOB_STATUS_NOT_STARTED = '3'
JOB_STATUS_FAILED = '4'